"""add bot_enabled to pts

Revision ID: c9d4f954b8b8
Revises: eaaac0aa6f71
Create Date: 2026-04-26 10:48:28.865089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d4f954b8b8'
down_revision: Union[str, Sequence[str], None] = 'eaaac0aa6f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pts', sa.Column('bot_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pts', 'bot_enabled')
    # ### end Alembic commands ###
